apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-frontend-service-config-map
data:
  PORT: "4000"
  USERS_URL: http://bookstore-users-service-service:3000
  BOOKS_URL: http://bookstore-books-service-service:3001
  REVIEWS_URL: http://bookstore-reviews-service-service:3002

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-users-service-config-map
data:
  PORT: "3000"
  DB_HOST: db-mysql-service-service
  DB_NAME: books_db

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-books-service-config-map
data:
  PORT: "3001"
  DB_HOST: db-mysql-service-service
  DB_NAME: books_db

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-reviews-service-config-map
data:
  PORT: "3002"
  DB_HOST: db-mysql-service-service
  DB_NAME: books_db