apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-users-service-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-users-service
      version: v1
  template:
    metadata:
      labels:
        app: bookstore-users-service
        version: v1
    spec:
      containers:
        - name: bookstore-users-service
          image: ernesqba/bookstore-users-service:v1
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bookstore-users-service-config-map
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookstore-users-service-config-map
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-users-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-users-service-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookstore-users-service-config-map
                  key: DB_NAME
          ports:
          - name: health-port
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: health-port
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: health-port
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bookstore-users-service-v1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookstore-users-service-v1
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50