apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service-service
spec:
  type: LoadBalancer
  selector:
    app: bookstore-frontend-service
  ports:
    - name: http-frontend
      protocol: TCP
      port: 4000
      targetPort: 4000