apiVersion: v1
kind: Service
metadata:
  name: db-mysql-service-service
spec:
  type: ClusterIP
  selector:
    app: db-mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  