apiVersion: v1
kind: Service
metadata:
  name: bookstore-users-service-service
spec:
  type: ClusterIP
  selector:
    app: bookstore-users-service
  ports:
    - name: http-users
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: bookstore-books-service-service
spec:
  type: ClusterIP
  selector:
    app: bookstore-books-service
  ports:
    - name: http-books
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: bookstore-reviews-service-service
spec:
  type: ClusterIP
  selector:
    app: bookstore-reviews-service
  ports:
    - name: http-reviews
      protocol: TCP
      port: 3002
      targetPort: 3002